### ISSUE TITLE
'Application' object has no attribute 'sessionID'

### ISSUE THREAD

**Issue by davitkh94** [rinleit/quickfix-sample-python#4]
Hi, I am trying to run the application and receive this error.

Traceback (most recent call last):
  File "client.py", line 29, in <module>
    main(args.file_name)
  File "client.py", line 17, in main
    application.run()
  File "C:\Users\Admin\Downloads\quickfix-python-samples-master\initiator\application.py", line 87, in run
    if options == '1':
  File "C:\Users\Admin\Downloads\quickfix-python-samples-master\initiator\application.py", line 80, in put_new_order

  File "C:\ProgramData\Anaconda3\lib\site-packages\quickfix.py", line 39558, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Application, name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\quickfix.py", line 83, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'Application' object has no attribute 'sessionID'
(base) PS C:\Users\Admin\Downloads\quickfix-python-samples-master\initiator>

Could you please kindly help me out with this error?

**Comment by davitkh94** [comment]
I have tried importing the SessionID (from quickfix import sessionID) and it doesn't resolve the problem.

**Comment by nduartegoodfill** [comment]
Hey, getting the same issue, did you ever get it fixed?

**Comment by rinlevan** [comment]
@nduartegoodfill Let try this #6
